=== jalguacilgon/PracticasABD/ABD T2 P2/Datos.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT autoescuela (alumnos, profesores, coches)> 

<!ELEMENT alumnos (alumno)+> 
<!ELEMENT profesores (profesor)+> 
<!ELEMENT coches (coche)+>  

<!ELEMENT alumno (examenTeoria, clasesPracticas, examenPractica)> 
<!ELEMENT profesor (nombre, apellido,edad,horasSemanalTeoria, (horasSemanalPractica)+)> 
<!ELEMENT coche (marca, modelo)> 

<!ELEMENT examenTeoria (#PCDATA)> 
<!ELEMENT clasesPracticas (#PCDATA)> 
<!ELEMENT examenPractica (#PCDATA)> 
<!ELEMENT nombre (#PCDATA)> 
<!ELEMENT apellido (#PCDATA)> 
<!ELEMENT edad (#PCDATA)> 
<!ELEMENT horasSemanalTeoria (#PCDATA)> 
<!ELEMENT horasSemanalPractica(#PCDATA)> 
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>

<!ATTLIST alumno alumnoId NMTOKEN #REQUIRED>
<!ATTLIST profesor profId NMTOKEN #REQUIRED> 
<!ATTLIST coche cocheId NMTOKEN #REQUIRED> 
<!ATTLIST coche anio CDATA #IMPLIED> 
<!ATTLIST horasSemanalPractica cocheId CDATA #REQUIRED> 
<!ATTLIST horasSemanalPractica horas CDATA #REQUIRED>
<!ATTLIST coche matricula ID #REQUIRED>

=== jalguacilgon/PracticasABD/ABD T2 P2/Autoescula.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE autoescuela SYSTEM "Datos.dtd">
<autoescuela>

	<alumnos>
		<alumno alumnoId="Jesus">
			<clasesPracticas>43</clasesPracticas>
			<examenPractica>3</examenPractica>
			<examenTeoria>1</examenTeoria>
		</alumno>
	
		<alumno alumnoId="Carlos">
			<clasesPracticas>43</clasesPracticas>
			<examenPractica>3</examenPractica>
			<examenTeoria>1</examenTeoria>
		</alumno>
		
		<alumno alumnoId="Ana">
			<clasesPracticas>43</clasesPracticas>
			<examenPractica>3</examenPractica>
			<examenTeoria>1</examenTeoria>
		</alumno>

		<alumno alumnoId="Rosa">
			<clasesPracticas>43</clasesPracticas>
			<examenPractica>3</examenPractica>
			<examenTeoria>1</examenTeoria>
		</alumno>

		<alumno alumnoId="Rodrigo">
			<clasesPracticas>43</clasesPracticas>
			<examenPractica>3</examenPractica>
			<examenTeoria>1</examenTeoria>
		</alumno>
	</alumnos>
	
	<profesores>
		<profesor profId="Juan">
			<nombre>Juan</nombre>
			<apellido>Gonzalez</apellido>
			<edad>39</edad>
			<horasSemanalTeoria>10</horasSemanalTeoria>
			<horasSemanalPractica>25<horasSemanalPractica/>
		</profesor>

		<profesor profId="Eva">
			<nombre>Eva</nombre>
			<apellido>Moreno</apellido>
			<edad>34</edad>
			<horasSemanalTeoria>5</horasSemanalTeoria>
			<horasSemanalPractica>30<horasSemanalPractica/>
		</profesor>
	</profesores>
	
	<coches>
		<coche matrcicula="6960GLC">
			<marca>Seat</marca>
			<modelo>Leon</modelo>
		</coche>
	
		<coche matricula="7953JCR">
			<marca>Renault</marca>
			<modelo>Megane</modelo>
		</coche>
	</coches>
	
</autoescuela>
